
CREATE DATABASE user_management_db
    WITH
    OWNER = developer
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE ROLE developer WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	BYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

COMMENT ON ROLE developer IS 'developer';

CREATE TABLE employee (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name varchar(60) NOT NULL,
	last_name varchar(60) NOT NULL,
	email varchar(20) UNIQUE NOT NULL,
	phone varchar(20),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE login (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
	username VARCHAR(60) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);