version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/workspace:cached
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devjava2026
      POSTGRES_DB: user_management_db
    ports:
      - "5432:5432"
